version: '3.7'

services:
  minecraft:
    container_name: 'minecraft-server'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/local/Minecraft_Server'
    working_dir: /usr/local/Minecraft_Server
    ports:
      - '25565:25565'
      - '25575:25575'
      - '8123:8123' # dynmap
    # command: ['sh', 'spigot-build.sh']
    # command: ['java', '-Xms1G', '-Xmx1G', '-jar', 'server.jar', 'nogui']
    command: ['java', '-Xms1G', '-Xmx1G', '-jar', 'spigot-server.jar', 'nogui']
