version: '3.7'

services:
  minecraft:
    container_name: 'minecraft-server'
    image: openjdk:8-jre-stretch
    volumes:
      - '.:/usr/local/Minecraft_Server'
    working_dir: /usr/local/Minecraft_Server
    ports:
      - '25565:25565'
    command: ['java', '-Xms1G', '-Xmx1G', '-jar', 'server.jar', 'nogui']
