version: '3.7'

services:
  minecraft:
    container_name: 'minecraft-server'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: 1.16.1
        BUILD: 89
    volumes:
      - '.:/usr/local/Minecraft_Server'
    ports:
      - '25565:25565'
      - '25575:25575'
      - '8123:8123' # dynmap
