version: '3.8'

services:
  minecraft:
    container_name: 'minecraft-server'
    image: 'rkunihiro/docker-minecraft-server:latest'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: 1.18.1
        BUILD: 175
        MCRCON: 0.7.2
    volumes:
      - '.:/usr/local/Minecraft_Server'
    ports:
      - '25565:25565'
      - '25575:25575'
      - '8123:8123' # dynmap
